### ISSUE TITLE
Add ability to reimport exported data

### ISSUE THREAD

**Issue by fbaligand** [alissonsales/esexport#3]
Currently, we can only export data, to a json format.
It would be great to be able to reimport the json file to a elasticsearch cluster, ideally, with the same "scoll" way, that is to say, using multiple `_bulk` API calls (one bulk call per 1000 documents for example)

**Comment by alissonsales** [comment]
Hi @fbaligand thanks for the suggestion, but this is not under the realm of problems I'm trying to solve with this small tool.

The feature you're describing sounds like [elasticsearch reindex api](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html).
